apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
        type: webserver1
    spec:
      containers:
      - name: app2
        image: supergiantkir/animals:moose
        ports:
        - containerPort: 80
